/**
 * Reports module barrel — ProofPilot (Phase 9)
 */

export {
  generateTechnicalReport,
  generateClientFacingReport,
  type TechnicalReport,
  type ReportMeta,
  type ReportRun,
  type ReportProject,
  type ReportEnvironment,
  type ReportConfig,
  type ReportPage,
  type ReportJourney,
  type ReportJourneyStep,
  type ReportFindings,
  type ReportFinding,
  type ReportSemanticGroup,
  type ReportPerformance,
  type ReportAccessibility,
  type ReportErrors,
  type GenerateTechnicalReportOptions,
  type GenerateTechnicalReportResult,
  type ClientFacingReport,
  type ClientBranding,
  type ClientExecutive,
  type ClientQuality,
  type ClientIssues,
  type ClientIssue,
  type GenerateClientFacingReportOptions,
} from './technical-report'

export {
  getWhiteLabelSettings,
  updateWhiteLabelSettings,
  resetWhiteLabelSettings,
  type WhiteLabelSettings,
  type UpdateWhiteLabelInput,
  type UpdateWhiteLabelResult,
} from './white-label'

export {
  createShare,
  verifyShareAccess,
  resolveShareInfo,
  revokeShare,
  getShare,
  listShares,
  generateSignedArtifactUrl,
  verifySignedArtifactUrl,
  SHARE_TOKEN_BYTES,
  SIGNED_ARTIFACT_EXPIRY_MINUTES,
  MAX_SHARES_PER_REPORT,
  type ShareType,
  type ShareAccessStatus,
  type CreateShareOptions,
  type CreateShareResult,
  type ShareAccessOptions,
  type ShareAccessResult,
  type ShareAccessDenied,
  type ShareDetails,
  type ListSharesResult,
  type SignedArtifactParams,
} from './secure-sharing'
